/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.TipoTrabajador;
import aplicacion.Trabajador;
import aplicacion.DatosAdicionalesTrabajadores;
import javax.swing.DefaultComboBoxModel;
import java.awt.Image;
import javax.swing.Icon;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VGestionTrabajador extends javax.swing.JDialog {

    /**
     * Creates new form VGestionTrabajador
     */
    private aplicacion.FachadaAplicacion fa;
    private VPrincipal padre;
    private Trabajador t;
    
    public VGestionTrabajador(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Trabajador t) {
        super(parent, modal);
        this.fa=fa;
        this.t= t;
        padre=(VPrincipal) parent;
        initComponents();
        CampoAgencia.setVisible(false);
        AgenciaLabel.setVisible(false);
        CampoNombreA.setVisible(false);
        NombreALabel.setVisible(false);
        CampoAfil.setVisible(false);
        AfilLabel.setVisible(false);
        CampoIP.setVisible(false);
        CampoIP.setEnabled(false);
        IpLabel.setVisible(false);
        CampoGrupo.setVisible(false);
        GrupoLabel.setVisible(false);
        ManLabel.setVisible(false);
        ComboBoxMan.setVisible(false);
        //ponemos los respectivos atributos en cada textfield para luego poder modificarlos
        CampoPasaporte.setText(t.getPasaporte());
        CampoNombre.setText(t.getNombre());
        CampoContacto.setText(t.getTelefono());
        CampoEmail.setText(t.getEmail());
        CampoUsername.setText(t.getUser());
        CampoContrasena.setText(t.getPassword());
        ComboBoxTipo.setSelectedItem(t.getTipoTrabajador());
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            actualizarCamposSegunTipo();
        }
        });
        List<Trabajador> listamanagers = fa.obtenerManagers();
        for (Trabajador tr : listamanagers) {
            ComboBoxMan.addItem(tr.getPasaporte());
        }
        List<DatosAdicionalesTrabajadores> lisotdato= fa.obtenerotdatos(t.getPasaporte());
        for(DatosAdicionalesTrabajadores ot: lisotdato){
            ComboBoxMan.setSelectedItem(ot.getManager());
            CampoIP.setText(ot.getIP().toString());
            CampoNombreA.setText(ot.getNombreArt());
            CampoAgencia.setText(ot.getAgencia());
            CampoAfil.setText(ot.getAfiliacion());
            CampoGrupo.setText(ot.getGrupo());
        }
    }
    
    public VGestionTrabajador(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        padre=(VPrincipal) parent;
        initComponents();
        CampoAgencia.setVisible(false);
        AgenciaLabel.setVisible(false);
        CampoNombreA.setVisible(false);
        NombreALabel.setVisible(false);
        CampoAfil.setVisible(false);
        AfilLabel.setVisible(false);
        CampoIP.setVisible(false);
        CampoIP.setEnabled(false);
        IpLabel.setVisible(false);
        CampoGrupo.setVisible(false);
        GrupoLabel.setVisible(false);
        ManLabel.setVisible(false);
        ComboBoxMan.setVisible(false);
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            actualizarCamposSegunTipo();
        }
        });
        List<Trabajador> listamanagers = fa.obtenerManagers();
        for (Trabajador t : listamanagers) {
            ComboBoxMan.addItem(t.getPasaporte());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoPasaporte = new javax.swing.JTextField();
        CampoNombre = new javax.swing.JTextField();
        CampoContacto = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoContrasena = new javax.swing.JTextField();
        CampoUsername = new javax.swing.JTextField();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        CampoNombreA = new javax.swing.JTextField();
        CampoIP = new javax.swing.JTextField();
        CampoGrupo = new javax.swing.JTextField();
        CampoAfil = new javax.swing.JTextField();
        CampoAgencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IpLabel = new javax.swing.JLabel();
        NombreALabel = new javax.swing.JLabel();
        GrupoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AgenciaLabel = new javax.swing.JLabel();
        AfilLabel = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        ComboBoxMan = new javax.swing.JComboBox<>();
        ManLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComboBoxTipo.setModel(new DefaultComboBoxModel(TipoTrabajador.values()));

        CampoIP.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Pasaporte:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Contacto:");

        jLabel4.setText("Email:");

        IpLabel.setText("IP registrada:");

        NombreALabel.setText("Nombre artista:");

        GrupoLabel.setText("Grupo:");

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        jLabel7.setText("Tipo:");

        AgenciaLabel.setText("Agencia:");

        AfilLabel.setText("Afiliación:");

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/mal.png"))); // NOI18N
        BotonSalir.setText("jButton1");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/bien.png"))); // NOI18N
        BotonGuardar.setText("jButton1");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        ComboBoxMan.setModel(new DefaultComboBoxModel());

        ManLabel.setText("Mánager:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(IpLabel)
                    .addComponent(NombreALabel)
                    .addComponent(GrupoLabel)
                    .addComponent(ManLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBoxMan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoIP, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoNombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(CampoPasaporte, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AgenciaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AfilLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoAfil, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgenciaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoAfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AfilLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IpLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreALabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrupoLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManLabel))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        anadirTrabajador();
        this.dispose();
    }//GEN-LAST:event_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfilLabel;
    private javax.swing.JLabel AgenciaLabel;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JTextField CampoAfil;
    private javax.swing.JTextField CampoAgencia;
    private javax.swing.JTextField CampoContacto;
    private javax.swing.JTextField CampoContrasena;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoGrupo;
    private javax.swing.JTextField CampoIP;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNombreA;
    private javax.swing.JTextField CampoPasaporte;
    private javax.swing.JTextField CampoUsername;
    private javax.swing.JComboBox<String> ComboBoxMan;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JLabel GrupoLabel;
    private javax.swing.JLabel IpLabel;
    private javax.swing.JLabel ManLabel;
    private javax.swing.JLabel NombreALabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
private void actualizarCamposSegunTipo() {
    // Ocultamos todos los campos primero
    CampoAgencia.setVisible(false);
    AgenciaLabel.setVisible(false);
    CampoNombreA.setVisible(false);
    NombreALabel.setVisible(false);
    CampoAfil.setVisible(false);
    AfilLabel.setVisible(false);
    CampoIP.setVisible(false);
    IpLabel.setVisible(false);
    CampoGrupo.setVisible(false);
    GrupoLabel.setVisible(false);
    ManLabel.setVisible(false);
    ComboBoxMan.setVisible(false);
    Object seleccionado = ComboBoxTipo.getSelectedItem();

    if (seleccionado == TipoTrabajador.Escritor || seleccionado == TipoTrabajador.Productor) {
        CampoIP.setVisible(true);
        IpLabel.setVisible(true);
        CampoAfil.setVisible(true);
        AfilLabel.setVisible(true);
    } else if (seleccionado == TipoTrabajador.Manager) {
        CampoAgencia.setVisible(true);
        AgenciaLabel.setVisible(true);
    } else if (seleccionado == TipoTrabajador.Artista) {
        CampoNombreA.setVisible(true);
        NombreALabel.setVisible(true);
        CampoGrupo.setVisible(true);
        GrupoLabel.setVisible(true);
        ManLabel.setVisible(true);
        ComboBoxMan.setVisible(true);
    }
}
private void anadirTrabajador(){
    String pasaporte = CampoPasaporte.getText();
    String nombre = CampoNombre.getText();
    String contacto = CampoContacto.getText();
    String email = CampoEmail.getText();
    String user = CampoUsername.getText();
    String password = CampoContrasena.getText();
    TipoTrabajador tipot = (TipoTrabajador) ComboBoxTipo.getSelectedItem();
    String tipo = tipot.name();
    String input = CampoIP.getText();
    String afiliacion = CampoAfil.getText();
    String agencia = CampoAgencia.getText();
    String nombrear = CampoNombreA.getText();
    String grupo = CampoGrupo.getText();
    String pasaporteM = (String) ComboBoxMan.getSelectedItem();
    fa.anadirTrabajador(pasaporte, nombre, contacto, email, user, password, tipo, afiliacion, agencia, nombrear, grupo, pasaporteM);
}

}
