/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.Premiacion;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.awt.Color;
/**
 *
 * @author alumnogreibd
 */
public class VGestionPremios extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;
    private VPrincipal padre;
    private Premiacion p;
    private int tipoPremio = -1;
    /**
     * Creates new form VGestionPremios
     */
    public VGestionPremios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Premiacion p) {
        super(parent, modal);
        this.fa = fa;
        this.p = p;
        initComponents();
        CampoNombre.setText(p.getPremio().getNombre());
        CampoNombre.setBackground(Color.LIGHT_GRAY);
        CampoNombre.setEnabled(false);
        CampoInst.setText(p.getPremio().getInstitucion());
        CampoFecha.setText(p.getFechaPremiacion().toString());
        if(p.getAlbum() != null){
            tipoPremio = 1;
            CampoCanAlb.setText(p.getAlbum());
            BotonAlbum.setBackground(Color.GREEN);
            BotonCancion.setBackground(Color.LIGHT_GRAY);
            BotonCancion.setEnabled(false);
        }
        if(p.getCancion() != null){
            tipoPremio = 0;
            CampoCanAlb.setText(p.getCancion());
            BotonCancion.setBackground(Color.GREEN);
            BotonAlbum.setBackground(Color.LIGHT_GRAY);
            BotonAlbum.setEnabled(false);
        }
        
    }
    public VGestionPremios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        CampoNombre.setBackground(Color.WHITE);
        CampoNombre.setEnabled(true);
        BotonCancion.setEnabled(true);
        BotonAlbum.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoInst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonCancion = new javax.swing.JButton();
        BotonAlbum = new javax.swing.JButton();
        CampoCanAlb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Institucion:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Para:");

        BotonCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/cancion.png"))); // NOI18N
        BotonCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancionActionPerformed(evt);
            }
        });

        BotonAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/album.png"))); // NOI18N
        BotonAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlbumActionPerformed(evt);
            }
        });

        jLabel5.setText("Álbum/canción premiada:");

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/bien.png"))); // NOI18N
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iloveimg-resized(2)/mal.png"))); // NOI18N
        BotonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoInst, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoCanAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCanAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(BotonCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonGuardar1ActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        anadirPremio();
        this.dispose();
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancionActionPerformed
        // TODO add your handling code here:
        tipoPremio = 0;
        BotonCancion.setBackground(Color.GREEN);
        BotonAlbum.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BotonCancionActionPerformed

    private void BotonAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlbumActionPerformed
        // TODO add your handling code here:
        tipoPremio = 1;
        BotonAlbum.setBackground(Color.GREEN);
        BotonCancion.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BotonAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlbum;
    private javax.swing.JButton BotonCancion;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonGuardar1;
    private javax.swing.JTextField CampoCanAlb;
    private javax.swing.JTextField CampoFecha;
    private javax.swing.JTextField CampoInst;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
private void anadirPremio(){
    String nombre = CampoNombre.getText();
    String institucion = CampoInst.getText();
    String textfecha = CampoFecha.getText();
    LocalDate fecha = LocalDate.parse(textfecha);
    String nombrealbcan = CampoCanAlb.getText();
    fa.anadirPremio(nombre, institucion, fecha, tipoPremio, nombrealbcan);
}
}
